dts:
  # 开发者应该设置成自己的wx相关信息
  wx:
    app-id: 123123
    app-secret: 123x
    mch-id: 123123
    mch-key: 123123
    notify-url: https://test.dtsshop.com/demo/order/dtsNotify
    # 商户证书文件路径
    # 请参考“商户证书”一节 https://pay.weixin.qq.com/wiki/doc/api/wxa/wxa_api.php?chapter=4_3
    key-path: 123123x

 #通知相关配置
  notify:
    mail:
      # 邮件通知配置,邮箱一般用于接收业务通知例如收到新的订单，sendto 定义邮件接收者，通常为商城运营人员
      enable: true
      host: smtp.aliyun.com
      username: dtsshop@aliyun.com
      password: 123x
      sendfrom: 123x@aliyun.com
      sendto: 123x@qq.com

    # 短消息模版通知配置
    # 短信息用于通知客户，例如发货短信通知，注意配置格式；template-name，template-templateId 请参考 NotifyType 枚举值
    sms:
      enable: true
      appid: 123
      appkey: 123
      template:
      - name: paySucceed
        templateId: 112233
      - name: captcha
        templateId: 112233
      - name: ship
        templateId: 112233
      - name: refund
        templateId: 112233

    # 微信模版通知配置
    # 微信模版用于通知客户或者运营者，注意配置格式；template-name，template-templateId 请参考 NotifyType 枚举值
    wx:
      enable: true
      template:
      - name: paySucceed
        templateId: sirUcgTAIQfoI123123123
      - name: captcha
        templateId: OfBkXh7UILpsDkc123123123
      - name: ship
        templateId: dqTuWzrmL_wwK-SJs123123123
      - name: applyRefund
        templateId: lzPHltMpUOiBol7i2Y123123123
      - name: refund
        templateId: NDy6EpPuu2C9NMU123123123

  # 快鸟物流查询配置
  express:
    enable: true
    appId: "1683286"
    appKey: "50a29285-0d3a-4e86-afb8-d92275ec9cd8"
    vendors:
    - code: "HTKY"
      name: "百世快递"
    - code: "YZBK"
      name: "邮政国内标快"
    - code: "ZTO"
      name: "中通快递"
    - code: "YTO"
      name: "圆通速递"
    - code: "YD"
      name: "韵达速递"
    - code: "YZPY"
      name: "邮政快递包裹"
    - code: "EMS"
      name: "EMS"
    - code: "DBL"
      name: "德邦快递"
    - code: "FAST"
      name: "快捷快递"
    - code: "ZJS"
      name: "宅急送"
    - code: "TNT"
      name: "TNT快递"
    - code: "UPS"
      name: "UPS"
    - code: "DHL"
      name: "DHL"
    - code: "FEDEX"
      name: "FEDEX联邦(国内件)"
    - code: "FEDEX_GJ"
      name: "FEDEX联邦(国际件)"

  # 对象存储配置
  storage:
    # 当前工作的对象存储模式，分别是local、aliyun、tencent、qiniu
    active: local
    # 本地对象存储配置信息
    local:
      storagePath: dts/storage
      # 这个地方应该是wx模块的WxStorageController的fetch方法对应的地址
      address: http://localhost:8080/demo/storage/
    # 阿里云对象存储配置信息
    aliyun:
      endpoint: oss-cn-guangzhou.aliyuncs.com
      accessKeyId: 111111
      accessKeySecret: 123123123
      bucketName: dts-shop
    # 腾讯对象存储配置信息
    # 请参考 https://cloud.tencent.com/document/product/436/6249
    tencent:
      secretId: 111111
      secretKey: 123
      region: 123123123
      bucketName: dts
    # 七牛云对象存储配置信息
    qiniu:
      endpoint: http://cdn.szzfb.club
      accessKey: UPSO2MA5ZT9YU2rGAp1G_JfHeRJhPuTFDtrFfF7N
      secretKey: YqBJ-apvJQjVjnYX7f36d6QudybFUN4yjRAPDSWg
      bucketName: myzfimgs
      
pagehelper:
  helperDialect:  mysql
  reasonable: true
  supportMethodsArguments:  true
  params: count=countSql

spring:
  datasource:
    druid:
      url:  jdbc:mysql://localhost:3306/myshop?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false
      driver-class-name:  com.mysql.jdbc.Driver
      username:  root
      password:  admin123
      initial-size:  10
      max-active:  50
      min-idle:  10
      max-wait:  60000
      pool-prepared-statements:  true
      max-pool-prepared-statement-per-connection-size:  20
      validation-query:  SELECT 1 FROM DUAL
      test-on-borrow:  false
      test-on-return:  false
      test-while-idle:  true
      time-between-eviction-runs-millis:  60000
      filters:  stat,wall